/* Generated by gen_stubs.py from apktool smali -- DO NOT HAND EDIT.
 * 159 native methods in 158 classes; 158 short + 159 long JNI symbols.
 * Normal natives receive (JNIEnv*, jobject); FastNative/CriticalNative
 * take no args (so arg-passing convention mismatches are harmless).
 */

#include <jni.h>

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeConvertAndroid420ToABGR(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeConvertAndroid420ToABGR__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IIILandroid_view_Surface_2Ljava_nio_ByteBuffer_2IIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeConvertAndroid420ToBitmap(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeConvertAndroid420ToBitmap__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IIILandroid_graphics_Bitmap_2III(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeCopyBetweenByteBufferAndBitmap(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeCopyBetweenByteBufferAndBitmap__Landroid_graphics_Bitmap_2Ljava_nio_ByteBuffer_2IIIIZ(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeRotateYUV(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeRotateYUV__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2III(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeShiftPixel(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeShiftPixel__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2IIIIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeWriteJpegToSurface(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_camera_core_ImageProcessingUtil_nativeWriteJpegToSurface___3BLandroid_view_Surface_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jintArray JNICALL
Java_androidx_camera_core_impl_utils_SurfaceUtil_nativeGetSurfaceInfo(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT jintArray JNICALL
Java_androidx_camera_core_impl_utils_SurfaceUtil_nativeGetSurfaceInfo__Landroid_view_Surface_2(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT jlong JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeCreateSharedCounter(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeCreateSharedCounter__I(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeGetCounterValue(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeGetCounterValue__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeIncrementAndGetCounterValue(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeIncrementAndGetCounterValue__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeTruncateFile(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_datastore_core_NativeSharedCounter_nativeTruncateFile__I(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_ConicConverter_internalConicToQuadratics(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_ConicConverter_internalConicToQuadratics___3FI_3FFF(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_createInternalPathIterator(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_createInternalPathIterator__Landroid_graphics_Path_2IF(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_destroyInternalPathIterator(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_destroyInternalPathIterator__J(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jboolean JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorHasNext(void)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorHasNext__J(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorNext(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorNext__J_3FI(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorPeek(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorPeek__J(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorRawSize(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorRawSize__J(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorSize(void)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_androidx_graphics_path_PathIteratorPreApi34Impl_internalPathIteratorSize__J(void)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onAppOpenAttributionNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onAppOpenAttributionNative__Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onAttributionFailureNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onAttributionFailureNative__Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onDeepLinkingNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onDeepLinkingNative__Lcom_appsflyer_deeplink_DeepLinkResult_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onInstallConversionDataLoadedNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onInstallConversionDataLoadedNative__Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onInstallConversionFailureNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onInstallConversionFailureNative__Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onResponseErrorNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onResponseErrorNative__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onResponseNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_appsflyer_AppsFlyer2dXConversionCallback_onResponseNative__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getEstimatedExposure(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getEstimatedExposure__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getEstimatedMarginAdjustment(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getEstimatedMarginAdjustment__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getGridBotEstLiquidationPrice(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getGridBotEstLiquidationPrice__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getLiquidationPrice(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getLiquidationPrice__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMarginReq(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMarginReq__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMaxSizeByContract(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMaxSizeByContract__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMaxSizeByUSDT(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getMaxSizeByUSDT__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getQuantity(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getQuantity__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getSpecificPrice(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getSpecificPrice__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getValue(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_example_project_ndk_ShareLib_getValue__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_D8871(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_D8871__Landroid_content_Context_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jint JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_N14263A23323(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_N14263A23323__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jstring JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_component5(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_component5__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_component9(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_component9__Landroid_content_Context_2Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_setPivotYN16904(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_setPivotYN16904__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_setTopP6481(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_setTopP6481__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_vD14832N6715(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_fingerprintjs_android_fpjs_1pro_1internal_cb_vD14832N6715__Ljava_util_List_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jstring JNICALL
Java_com_geetest_gtc4_Core_getData(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_geetest_gtc4_Core_getData__Landroid_content_Context_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_geetest_gtc4_Core_getData__Landroid_content_Context_2Lcom_geetest_gtc4_GeeGuardConfiguration_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT void JNICALL
Java_com_google_android_gms_tasks_NativeOnCompleteListener_nativeOnComplete(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_google_android_gms_tasks_NativeOnCompleteListener_nativeOnComplete__JLjava_lang_Object_2ZZLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_closeNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_closeNative__J(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jlong JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_createNativeWithClientOptions(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_createNativeWithClientOptions___3B(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeBitmapNative(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeBitmapNative__JLandroid_graphics_Bitmap_2Lcom_google_android_libraries_barhopper_RecognitionOptions_2(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeBufferNative(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeBufferNative__JIILjava_nio_ByteBuffer_2Lcom_google_android_libraries_barhopper_RecognitionOptions_2(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeNative(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT jbyteArray JNICALL
Java_com_google_android_libraries_barhopper_BarhopperV3_recognizeNative__JII_3BLcom_google_android_libraries_barhopper_RecognitionOptions_2(JNIEnv* env, jobject self)
{
    return (*env)->NewByteArray(env, 0);;
}

JNIEXPORT void JNICALL
Java_com_google_firebase_crashlytics_ndk_CrashpadMain_crashpadMain(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_google_firebase_crashlytics_ndk_CrashpadMain_crashpadMain___3Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jboolean JNICALL
Java_com_google_firebase_crashlytics_ndk_JniNativeApi_nativeInit(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_google_firebase_crashlytics_ndk_JniNativeApi_nativeInit___3Ljava_lang_String_2Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_clearEdgesNative(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_clearEdgesNative__(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectBlur(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectBlur___3BIIIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectBlurCaptureNative(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectBlurCaptureNative___3BIIIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectEdges(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectEdges___3BIIIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectGlare(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectGlare___3BIIIIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectPathReallyExist(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_detectPathReallyExist__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_extractMRZ(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_com_onfido_android_sdk_capture_native_1detector_NativeDetector_extractMRZ___3BIIIIII_3BIIII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_scottyab_rootbeer_RootBeerNative_checkForRoot(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_scottyab_rootbeer_RootBeerNative_checkForRoot___3Ljava_lang_Object_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages__Z(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_getArpCache(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_getArpCache__I(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getBaseApkPath(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getBaseApkPath__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getClonerFileData(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getClonerFileData__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getHostsModifiedTime(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getHostsModifiedTime__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getKeyFormat(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getKeyFormat__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getKeyValue(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getKeyValue__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativeAppVersion(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativeAppVersion__Landroid_content_Context_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativePackage(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativePackage__Landroid_content_Context_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativeSignature(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getNativeSignature__Landroid_content_Context_2(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPayloadFormat(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPayloadFormat__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPayloadTransformation(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPayloadTransformation__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPb(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_com_shield_android_internal_NativeUtils_getPb__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isAccessedSuperuserApk(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isAccessedSuperuserApk__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isChaosDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isChaosDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isDetectedDevKeys(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isDetectedDevKeys__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isDetectedTestKeys(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isDetectedTestKeys__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundBusyboxBinary(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundBusyboxBinary__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundDangerousProps(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundDangerousProps__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundMagisk(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundMagisk__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundResetprop(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundResetprop__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundSuBinary(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundSuBinary__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundSubstrate(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundSubstrate__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundWrongPathPermission(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundWrongPathPermission__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundXposed(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFoundXposed__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFridaDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isFridaDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isGboxDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isGboxDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isJiaguDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isJiaguDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isLsplantDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isLsplantDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isNotFoundReleaseKeys(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isNotFoundReleaseKeys__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_isPathExists(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_isPathExists__Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isPermissiveSelinux(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isPermissiveSelinux__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isSandHookDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isSandHookDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isSuExists(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isSuExists__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isTaichiDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isTaichiDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualAndroidDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualAndroidDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualCameraAppDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualCameraAppDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualXposedDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isVirtualXposedDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isZygiskDetected(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_isZygiskDetected__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_jitCacheCount(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_com_shield_android_internal_NativeUtils_jitCacheCount__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_listenForFrida(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_com_shield_android_internal_NativeUtils_listenForFrida__(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_com_shield_android_internal_NativeUtils_setClonerFileData(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_com_shield_android_internal_NativeUtils_setClonerFileData__Ljava_lang_String_2Ljava_lang_String_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_InterpreterFactoryImpl_nativeRuntimeVersion(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_InterpreterFactoryImpl_nativeRuntimeVersion__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_InterpreterFactoryImpl_nativeSchemaVersion(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_InterpreterFactoryImpl_nativeSchemaVersion__(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allocateTensors(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allocateTensors__JJ(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allowBufferHandleOutput(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allowBufferHandleOutput__JZ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allowFp16PrecisionForFp32(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_allowFp16PrecisionForFp32__JZ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createCancellationFlag(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createCancellationFlag__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createInterpreter(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createInterpreter__JJIZLjava_util_List_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createModel(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createModel__Ljava_lang_String_2J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createModelWithBuffer(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_createModelWithBuffer__Ljava_nio_ByteBuffer_2J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_delete(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_delete__JJJ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_deleteCancellationFlag(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_deleteCancellationFlag__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getExecutionPlanLength(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getExecutionPlanLength__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputCount(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputCount__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputNames(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputNames__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputTensorIndex(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getInputTensorIndex__JI(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputCount(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputCount__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputNames(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputNames__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputTensorIndex(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getOutputTensorIndex__JI(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getSignatureKeys(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_getSignatureKeys__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_hasUnresolvedFlexOp(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_hasUnresolvedFlexOp__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_resizeInput(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_resizeInput__JJI_3IZ(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_run(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_run__JJ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_setCancelled(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapper_setCancelled__JJZ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapperExperimental_resetVariableTensors(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeInterpreterWrapperExperimental_resetVariableTensors__JJ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeAllocateTensors(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeAllocateTensors__JJ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetInputIndex(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetInputIndex__JLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetOutputIndex(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetOutputIndex__JLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetSignatureRunner(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetSignatureRunner__JLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetSubgraphIndex(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeGetSubgraphIndex__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeInputNames(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeInputNames__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeInvoke(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeInvoke__JJ(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeOutputNames(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeOutputNames__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeResizeInput(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_NativeSignatureRunnerWrapper_nativeResizeInput__JJLjava_lang_String_2_3I(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_TensorImpl_buffer(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jobject JNICALL
Java_org_tensorflow_lite_TensorImpl_buffer__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_create(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_create__JII(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_createSignatureInputTensor(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_createSignatureInputTensor__JLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_createSignatureOutputTensor(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_TensorImpl_createSignatureOutputTensor__JLjava_lang_String_2(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_delete(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_delete__J(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_dtype(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_dtype__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_TensorImpl_hasDelegateBufferHandle(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jboolean JNICALL
Java_org_tensorflow_lite_TensorImpl_hasDelegateBufferHandle__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_index(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_index__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_TensorImpl_name(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jstring JNICALL
Java_org_tensorflow_lite_TensorImpl_name__J(JNIEnv* env, jobject self)
{
    return (*env)->NewStringUTF(env, "");;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_numBytes(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_numBytes__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jfloat JNICALL
Java_org_tensorflow_lite_TensorImpl_quantizationScale(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jfloat JNICALL
Java_org_tensorflow_lite_TensorImpl_quantizationScale__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_quantizationZeroPoint(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_TensorImpl_quantizationZeroPoint__J(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_readMultiDimensionalArray(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_readMultiDimensionalArray__JLjava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jintArray JNICALL
Java_org_tensorflow_lite_TensorImpl_shape(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT jintArray JNICALL
Java_org_tensorflow_lite_TensorImpl_shape__J(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT jintArray JNICALL
Java_org_tensorflow_lite_TensorImpl_shapeSignature(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT jintArray JNICALL
Java_org_tensorflow_lite_TensorImpl_shapeSignature__J(JNIEnv* env, jobject self)
{
    return (*env)->NewIntArray(env, 0);;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeDirectBuffer(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeDirectBuffer__JLjava_nio_Buffer_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeMultiDimensionalArray(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeMultiDimensionalArray__JLjava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeScalar(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_TensorImpl_writeScalar__JLjava_lang_Object_2(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_createDelegate(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jlong JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_createDelegate__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IZZZJ(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_deleteDelegate(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT void JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_deleteDelegate__J(JNIEnv* env, jobject self)
{
    return;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_getNnapiErrno(JNIEnv* env, jobject self)
{
    return 0;;
}

JNIEXPORT jint JNICALL
Java_org_tensorflow_lite_nnapi_NnApiDelegateImpl_getNnapiErrno__J(JNIEnv* env, jobject self)
{
    return 0;;
}
